### ISSUE TITLE
NAs produced by integer overflow 

### ISSUE THREAD

**Issue by alikiadaliri** [gaoming96/mcca#1]
Hi,
I am using the latest mcca package and have a three level outcome with sample size in each level as follows: n1=10360, n2=6604, and n3=1029. When I try to calculate pdi, it gives the error message "In length(n1) * length(n2) * length(n3) : NAs produced by integer overflow".

**Comment by gaoming96** [comment]
Hi,

I suppose 'NAs produced by integer overflow' means the value you want to
calculate exceeds maximum in R. R uses 32-bit integers for integer vectors,
so the range of representable integers is restricted to about +/-2*10^9,
while 54-bit integers for numeric vectors. You could find the information
by running .Machine$integer.max or reading help information ?integer .

If this is the case, the simplest way is to coerce it numeric: just use
as.numeric() or as.double().

For more information, please check:
https://stackoverflow.com/questions/17650803/r-simple-multiplication-causes-
integer-overflow

Best,
Ming

**Comment by gaoming96** [comment]
Hi,
I suppose 'NAs produced by integer overflow' means the value you want to calculate exceeds maximum in R. R uses 32-bit integers for integer vectors, so the range of representable integers is restricted to about +/-2*10^9, while 54-bit integers for numeric vectors. You could find the information by running .Machine$integer.max or reading help information ?integer .

If this is the case, the simplest way is to coerce it numeric: just use as.numeric() or as.double().

For more information, please check: 
https://stackoverflow.com/questions/17650803/r-simple-multiplication-causes-integer-overflow

Best,
Ming

**Comment by alikiadaliri** [comment]
Great, it worked. 
Thanks!
